### PR TITLE
Change theme to material

### PR DESCRIPTION
**Pull request by pktiuk**
We could also tweak this theme a bit:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme

### CODE REVIEW

**Comment by pktiuk** [comment]
@rolandlo 
Could you look at this?

**Comment by rolandlo** [comment]
@pktiuk I will look at it. Just give me some time.

**Comment by rolandlo** [comment]
Thanks for this PR. 
About the color-scheme: I kind of like indigo more as a primary color than blue. It is more calm and adds less distraction. In my opinion it would make sense to have a different accent color, because having some visual indication when you are hovering over a link seems desirable. So what about primary: indigo, accent: one of blue/light blue/deep purple/deep orange? The combination indigo/deep orange would be similar to the color combination used for the icon. 
What are your thoughts?

**Comment by pktiuk** [comment]
First of I want to tell I am not very experienced in terms of graphic design.
Although I like the idea of these orange accents, they look good.
I think primary color of site should be somehow associated with application, but in this case I don't see any matching color (maybe in this case it could be associated with Xournal++ mobile, which uses indigo :) ).

**Review by rolandlo — APPROVED** [review]
LGTM

**Pull request merged**
