### PR TITLE
Improve installation instructions for MacOS

### LINKED ISSUE #54: Note on macOs installation
**Affects versions :**
 - OS: Mac
 - Version of Xournal++: docs

**Describe the bug**
You suggested to improve the macOs installation guide, so here is a proposed change.

"Just download the archive and run the unzipped executable.”
⟶
1. Download the archive.
2. Move the unzipped executable to the Apps folder.
3. Right-click the executable and choose "Open”.
4. Read the prompt and confirm (if you want to use the program).
5. Once confirmed, you can run it like other programs.

**To Reproduce**
If you just double-click the executable the first time, macOs will not run it.

### PR DESCRIPTION
**Pull request by LittleHuba**
Steps provided in https://github.com/xournalpp/xournalpp/issues/3342

- [ ] I'd like to add some images here as well.
- [ ] Step 2 is still quite unspecific

Fixes  #54

### CODE REVIEW

**Comment by LittleHuba** [comment]
@maciej-radziejewski would you mind providing some images and specifying step two some more?

**Comment by maciej-radziejewski** [comment]
My system is in Polish, so the screenshots might not be accessible to a wider audience.

Anyway, each Mac has a standard Applications folder and this is where all the apps should be. Most Mac users know that, and if someone does not, this is not the place to teach them Mac basics.

I propose to either re-word Step 2 as:

> 2. Drag the unzipped executable to your Mac's Applications folder.

or leave out Step 2 and re-word the current Step 3 as "Right-click the unzipped executable… ."

**Comment by Technius** [comment]
We can do this with #51.

**Comment by Technius** [comment]
Now that #51 has been merged, this PR can go ahead.

**Comment by Technius** [comment]
I rebased & updated the installation instructions.

**Comment by rolandlo** [comment]
I have made a screen recording about how the installation process works on MacOS:

https://user-images.githubusercontent.com/40485433/153562186-c4b5844a-484c-417b-bbcf-e074b824a01e.mov

At least on my system, I always have to right click (or CTRL+click) and "Open" twice until I can launch Xournal++ successfully.

**Comment by Technius** [comment]
I updated the instructions with a link to Roland's video, and I added an extra step for newer versions of MacOS that require two attempts to open the application.

We should consider distributing as a `.dmg` (e.g., [as outlined here](https://developer.apple.com/library/archive/documentation/Porting/Conceptual/PortingUnix/distributing/distibuting.html)) instead of a `.zip` to simplify the installation process.

**Pull request merged**
