### PR TITLE
Complete Redesign of the Installation Page

### PR DESCRIPTION
**Pull request by Fatih20**
Continuation of #50

To do:
- [x] Use overrides to remove the pesky footer at the bottom and pencil tool at the header, without losing markdown extension that is used for generating tabs.
- [x] Correct the way that the individual OS' installation page links to other OS's installation page
- [x] Investigate why the variables in extras isn't read by the installation overrides

### CODE REVIEW

**Comment by Fatih20** [comment]
https://user-images.githubusercontent.com/51940383/129447064-cb564838-5b0e-4745-9c10-849406230861.mp4

The site as of right now.

**Comment by Fatih20** [comment]
I read a bit about the macros here https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced.html#including-snippets-in-pages. But I'm assuming what we're going to do is make an override like the home page with an HTML file, and then include snippets of the content from a markdown file. Yet it's not explicitly mentioned that you can include markdown files in HTML. However, it's mentioned you can include snippets of HTML in a markdown file. Is my assumption wrong and what you actually meant is the other way around?

**Comment by Fatih20** [comment]
I've looked into the macros plugin and from what I've tried, it is possible to include markdown files in HTML files. The problem now is that the documentation doesn't seem to mention a way to include just part of the included markdown files.

**Comment by Fatih20** [comment]
@Technius can you elaborate further on how we are going to make overrides but still having the content in the markdown files? Because I don't really understand.

**Comment by Technius** [comment]
We create an override for `installation/`. This override should contain the common elements, like the markup for the buttons at the top. We can select which button is "active" by [reading metadata](https://www.mkdocs.org/dev-guide/themes/#pagemeta) from the markdown files (e.g., at the top of the Windows file, we can set `active_button: windows`). To include the markdown content, we can use the `page.content` variable.

The individual markdown files should have the OS-specific instructions. In this case, the markdown files should just contain the contents of the `installation-guide` div.

**Comment by Fatih20** [comment]
Here's thing though. I'm assuming making the overrides for the installation page is the same process as making the overrides for the homepage. I repeated the process of moving the file to an HTML to the overrides folder with all of its CSS. For some reason, the page wouldn't read the CSS and go about unstyled. Even weirder is that the table of content is still visible even though we're supposed to override the theme. This didn't happen with the homepage.

**Comment by Fatih20** [comment]
> We create an override for `installation/`. This override should contain the common elements, like the markup for the buttons at the top. We can select which button is "active" by [reading metadata](https://www.mkdocs.org/dev-guide/themes/#pagemeta) from the markdown files (e.g., at the top of the Windows file, we can set `active_button: windows` and then using if/else to determine which button should get the active class). To include the markdown content, we can use the `page.content` variable.
> 
> The individual markdown files should have the OS-specific instructions. In this case, the markdown files should just contain the contents of the `installation-guide` div.

Wouldn't this mean clicking the OS selection button wouldn't link to the OS page? So is it replaced with an if/else logic that select which content is displayed according to what button is "active"? But what happens when there is no active button, such as when the user first visit the installation page?

**Comment by Fatih20** [comment]
On a second thought, could the overriding be a part of a different PR? Seems to me that it would also involve optimizing redundancies in the markdown. Which considering that some part are more complex to optimize, (Linux installation page has different download buttons, and the title of the version selection has a subtitle that isn't present in Windows and MacOS installation page), for the best implementation I think it should be a different PR.

**Comment by Fatih20** [comment]
image

For some reason that I don't know, MkDocs just wouldn't read the CSS linked to the `installation.html`. `<style>` still works, for some reason. The only reason it is being somewhat styled is the CSS from the `/docs/css` directory. If they are removed (which they should because they're specific to the installation page), it'll be like this.
image

Even worse is that for some reason, the table of content is still present. The homepage didn't do any of this in my previous pull request.

**Comment by Technius** [comment]
Yeah, let's just keep it simple for now. I can help you clean it up in another PR.

**Comment by Fatih20** [comment]
Alright, that problem is fixed. But now when building, MkDocs says that 'downloads' (which is in the individual OS installation page) is undefined. Even though it is defined in the `.yml` file. Any help? @Technius

**Comment by Fatih20** [comment]
I added the whole downloads variable to the header of the markdown only as a temporary measure. Once the layout is corrected I'll fix it.

**Comment by Technius** [comment]
You'll probably need to resort to the markdown file for Linux, otherwise you'll have to enter `<code>` tags manually.

> I added the whole downloads variable to the header of the markdown only as a temporary measure.

For the links, the "correct" solution would probably be something like defining the links in a yml file and then including it with a macro: https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#including-external-yaml-files

**Comment by Fatih20** [comment]
> You'll probably need to resort to the markdown file for Linux, otherwise you'll have to enter `<code>` tags manually.
What do you mean? You mean for the tabs and such or just the instruction within the tabs? I'm currently running into another problem where even when I break off the tab section to a markdown file (just like how the homepage "automate" the feature showcases)  it won't create a tab. Resulting in something like this :
image

**Comment by Technius** [comment]
The issue seems to be that markdown can't be used inside of manually inserted HTML tags. The simplest workaround I can think of is to put the tab element thing (the one that contains all of the tabs) into a markdown file and then use the include macro.

**Comment by Fatih20** [comment]
> The issue seems to be that markdown can't be used inside of manually inserted HTML tags. The simplest workaround I can think of is to put the tab element thing (the one that contains all of the tabs) into a markdown file and then use the include macro.

I've done this. Now I just need to theme it.

**Comment by Fatih20** [comment]
I don't get why using `{{ ' ../linux' | url }}` in the Windows installation page to link to the Linux installation page links to `http://127.0.0.1:8000/linux`. Shouldn't it go up a directory and then go to `linux`? Why is it not using relative path?

**Comment by Fatih20** [comment]
While this doesn't mitigate the problem completely, I believe this is a more elegant stopgap solution than merely putting the links in the header of the markdown. @Technius

**Comment by Technius** [comment]
Let's just get something working for now. I will clean it up later.

**Comment by Fatih20** [comment]
> Let's just get something working for now. I will clean it up later.

It's already working. Have you not tried it?

**Comment by Technius** [comment]
The install pages look fine to me for now.

> I don't get why using `{{ ' ../linux' | url }}` in the Windows installation page to link to the Linux installation page links to `http://127.0.0.1:8000/linux`. Shouldn't it go up a directory and then go to linux? Why is it not using relative path?

I think this is a mkdocs bug; the url filter should be generating the linux relative to the current page, but it's generating the link relative to the site's base url instead. For now, let's just directly write the url instead of using the filter.

**Comment by Fatih20** [comment]
> The install pages look fine to me for now.
> 
> > I don't get why using `{{ ' ../linux' | url }}` in the Windows installation page to link to the Linux installation page links to `http://127.0.0.1:8000/linux`. Shouldn't it go up a directory and then go to linux? Why is it not using relative path?
> 
> I think this is a mkdocs bug; the url filter should be generating the linux relative to the current page, but it's generating the link relative to the site's base url instead. For now, let's just directly write the url instead of using the filter.

```
<div class="OS-option-container">
        <a class="OS-option button" href="{{ 'installation/windows/' | url }}">Windows</a>
        <a class="OS-option button clicked" href="#">Linux</a>
        <a class="OS-option button" href="{{ 'installation/macos/' | url }}">MacOS</a>
</div>
```
As of right now these are the links used in the Linux installation page. Do I still need to change this?

**Comment by Fatih20** [comment]
Done.

**Review by Technius — APPROVED** [review]
I think this is good to go. I will handle the squash and final merge.

**Comment by Technius** [comment]
Sorry it took so long, I've been busy recently.

**Comment by Technius** [comment]
I pushed some commits to master branch to refactor the installation page template code. Some minor visual changes happened; can you check to see if it looks okay?

**Comment by Fatih20** [comment]
> I pushed some commits to master branch to refactor the installation page template code. Some minor visual changes happened; can you check to see if it looks okay?

Just saw it. Can't find any difference.

**Comment by Technius** [comment]
Thanks for checking!

**Pull request merged**
